# https://cloud.google.com/deep-learning-containers/docs/choosing-container

apiVersion: batch/v1
kind: Job
metadata:
  name: celltype-train-tpu
spec:
  # parallelism: 8  # Matches number of preemptables. This is the queue size.
  template:
    metadata:
      annotations:
        # The Cloud TPUs that will be created for this Job will support
        # TensorFlow 2.2. This version MUST match the
        # TensorFlow version that your model is built on.
        tf-version.cloud-tpus.google.com: "2.3"
    spec:
      securityContext:
        runAsUser: 0
      restartPolicy: Never
      containers:
      - name: celltype-train-tpu
        # The official TensorFlow 1.15.2 image.
        # https://hub.docker.com/r/tensorflow/tensorflow
        # image: tensorflow/tensorflow:1.15.2
        # image: tensorflow/tensorflow:2.3.0
        image: gcr.io/deeplearning-platform-release/tf2-gpu.2-3
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            apt-get update
            apt-get install git-all
            git clone https://github.com/drewlinsley/connectomics_gcp.git &&
            cd connectomics_gcp &&
            pip3 install --upgrade pip &&
            pip3 install -r requirements.txt &&
            pip3 install -U tpunicorn &&
            export PATH="$HOME/.local/bin:$PATH" &&
            pu list &&
            EXP_NAME=unet_celltyper
            bash src/run/train_celltype.sh $EXP_NAME $(KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS)
        resources:
          limits:
            # Request a single Preemptible v2-8 Cloud TPU device to train the
            # model. A single v2-8 Cloud TPU device consists of 4 chips, each of
            # which has 2 cores, so there are 8 cores in total.
            cloud-tpus.google.com/preemptible-v3: 256
